travis:
  secure:
    BINSTAR_TOKEN: ii+fCI0D3DFaaSXbwqsl6xrvzPxRaFWdK+p3fy5OERUnoSdf9zzXat6jwbexiYROQGPlQIgL8YQp8P0YQx9VrgWVzAHXxxcTT7qKdRLCfGQkBYmq68x5zEi0V6J0DirnpUcnw7BPeI+Ix74crtPRbFnxeiSl7ko/Xg61bAyxzOsDE11II50geCwH7+nORuaLimD9hsZo95GOvEnv/wLGZcI6uSNCZHL+cCzCxJhW+Axip72dK9tYxGPNvql83NOtu4PYv461ovJXlZVLiilbMm94cmQNuT1Jbgv4g/PX7/L9QH8PqyaBsrqqLVpQRUqaiSbN0aC0YpE/koWhQTObW9gAi/ERWaDH3eT7Winw9FJsh9WPbOnB3AWzUwAqJU0Lkg+VBgPOsdj+q9T/aFoEW0x0c8IY/uCQE5dyp3/z6565D3cGhf8Do3ZQMtlawOJ3UT5N3qLd9dYXhrQJPM8mG4OHBr8tGGO+YY4ycG+tzncMCy/HEnucCnvOAneduRbYQpP7EfnIaV9vflEpKjyAhnExdkXWDVHXib5qNe9O/d1gqUtPDC9oxNpgBzafed1ePBQnhH4hY/JB/l08ssztTVNFDw4FcNO0Bg2fRuYvvUckzsZ9I/it2meHAKUTrjWG322BKMDwDwDOSMRX4tHsymyfWTfZYnhFibyVuD4FpRc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
